[workspace]
members = [
    "rua-core",
    "rua-std-base",
    "rua-std-table",
    "rua-std-string",
    "rua-std-decl",
]

[workspace.package]
version = "0.2.1"
edition = "2024"
license = "MIT"
authors = ["Shiyu"]
description = "A short description of my package"
rust-version = "1.89"
default-run = "rua"
documentation = "https://example.com/bar"
