[workspace]
resolver = "2"
members = ["rua-core", "rua-std", "rua-std-macro"]

[workspace.package]
version = "0.2.1"
edition = "2024"
license = "MIT"
authors = ["Shiyu"]
description = "A short description of my package"
rust-version = "1.89"
documentation = "https://example.com/bar"

[profile.release]
lto = true
codegen-units = 1
strip = true
