[package]
name = "rua"
version = "0.1.1"
edition = "2021"

[lib]
name = "rua"
path = "src/lib.rs"

[[bin]] 
name = "ruac"
path = "src/bin/ruac.rs" 
bench = true 

[[bin]] 
name = "rua"
path = "src/bin/rua.rs" 
bench = true 

[dependencies]
